require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FileName:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
